services:
  discord-bot:
    build: .
    container_name: ZORSBOT
    env_file:
      - .env
    volumes:
        - ./assets:/app/assets
        - ./cogs:/app/cogs:ro
        - ./logs:/app/logs
    depends_on:
      - database

  database:
    image: postgres:17-alpine
    container_name: database
    restart: unless-stopped
    env_file:
      - .env