services:
  discord-bot:
    build: .
    container_name: ZORSBOT
    env_file:
      - .env
    volumes:
        - ./assets:/app/assets
        - ./cogs:/app/cogs:ro
        - ./logs:/app/logs
  database:
    image: postgres:16
    container_name: database
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d