services:
  discord-bot:
    image: ghcr.io/lolozendev/zorsbot:latest
    container_name: ZORSBot
    restart:
      unless-stopped
    env_file:
      - .env
    volumes:
        - ./runningbot/assets:/app/assets
        - ./runningbot/logs:/app/logs
        - ./runningbot/config/:/app/config/:ro
    depends_on:
      database:
          condition: service_healthy

  database:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    container_name: database
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data # Persist data even if container is removed
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
