services:
  discord-bot:
    build: .
    container_name: ZORSBOT
    env_file:
      - .env
    volumes:
        - ./runningbot/assets:/app/assets
        - ./runningbot/cogs:/app/cogs
        - ./runningbot/logs:/app/logs
    depends_on:
      - database

  database:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    container_name: database
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data # Persist data even if container is removed
