[tool.poetry]
name = "zorsbot"
version = "0.1.0"
description = "A discord bot for 'la bande s4' server"
authors = ["ZEN"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
colorlog = "^6.8.2"
py-cord = "^2.6.0"
requests = "^2.32.3"
prisma = "^0.13.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
