[tool.poetry]
name = "zorsbot"
version = "0.1.0"
description = "A discord bot for 'la bande s4' server"
authors = ["ZEN"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
py-cord = "^2.6.1"
requests = "^2.32.3"
loguru = "^0.7.2"
audioop-lts = "^0.2.1"
prisma = "^0.15.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
