name: Generate Docker image when new version of the bot is pushed to main

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'       # Matches v1.2
      - 'v[0-9]+.[0-9]+-RC[0-9]'   # Matches v1.2-RC1
      - 'v[0-9]+.[0-9]+.[0-9]+'     # Matches v1.2.3
      - 'v[0-9]+.[0-9]+.[0-9]+-RC[0-9]' # Matches v1.2.3-RC1

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: lowercase the image name
        run: |
            echo "IMAGE_NAME=$(echo ${{ github.repository }} | awk '{print tolower($0)}')" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: app
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest