name: Code Style Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pyrefly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install pyrefly
      - name: Run pyrefly (format)
        run: pyrefly . --check > pyrefly_output.txt
        continue-on-error: true

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install ruff
      - name: Run ruff (lint)
        run: ruff check . --output-format text > ruff_output.txt
        continue-on-error: true

  report:
    runs-on: ubuntu-latest
    needs: [pyrefly, ruff]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Générer le rapport Markdown
        run: python .github/scripts/generate_report.py
      - name: Ajouter le rapport au résumé
        run: echo "Rapport généré" # Remplacer par l'action souhaitée
