name: Code Style Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pyrefly:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set_output.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install pyrefly
      - name: Run pyrefly (format)
        id: run_pyrefly
        run: |
          pyrefly . --check >> $GITHUB_OUTPUT
        continue-on-error: true

  ruff:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set_output.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install ruff
      - name: Run ruff (lint)
        id: run_ruff
        run: |
          ruff check . --output-format text >> $GITHUB_OUTPUT
        continue-on-error: true

  report:
    runs-on: ubuntu-latest
    needs: [pyrefly, ruff]
    steps:
      - uses: actions/checkout@v4
      - name: Générer le rapport Markdown
        env:
          PYREFLY_RESULT: ${{ needs.pyrefly.outputs.result }}
          RUFF_RESULT: ${{ needs.ruff.outputs.result }}
        run: python .github/scripts/generate_report.py
      - name: Upload report
        run: cat report.md > $GITHUB_STEP_SUMMARY
