name: Code Style Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pyrefly:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set_output.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install pyrefly
      - name: Run pyrefly (format)
        run: pyrefly . --check > pyrefly_output.txt
        continue-on-error: true
      - name: Set output
        id: set_output
        run: echo "result<<EOF" >> $GITHUB_OUTPUT && cat pyrefly_output.txt >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT

  ruff:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set_output.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install ruff
      - name: Run ruff (lint)
        run: ruff check . --output-format text > ruff_output.txt
        continue-on-error: true
      - name: Set output
        id: set_output
        run: echo "result<<EOF" >> $GITHUB_OUTPUT && cat ruff_output.txt >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT

  report:
    runs-on: ubuntu-latest
    needs: [pyrefly, ruff]
    steps:
      - uses: actions/checkout@v4
      - name: Générer le rapport Markdown
        env:
          PYREFLY_RESULT: ${{ needs.pyrefly.outputs.result }}
          RUFF_RESULT: ${{ needs.ruff.outputs.result }}
        run: python .github/scripts/generate_report.py
